services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    command: ["fastapi", "run", "cwm_minio_api/app.py"]
    depends_on:
      - db

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "cwm"
      MINIO_ROOT_PASSWORD: "12345678"
    command:
      - server
      - /srv

volumes:
  db_data: {}
